---
# See https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/
apiVersion: 1
groups:
    - orgId: 1
      name: otel-demo
      folder: cart
      interval: 1m
      rules:
        - uid: des78nlna99tsf
          title: CartAddItemHighLatency
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: webstore-metrics
              model:
                editorMode: code
                expr: |-
                    histogram_quantile(
                      0.95,
                      sum by (le, deployment_environment_name, service_namespace, service_name) (
                        rate(
                          http_server_request_duration_seconds_bucket{
                            deployment_environment_name="",
                            service_namespace="opentelemetry-demo",
                            service_name="cart",
                            http_request_method="POST",
                            http_route="/oteldemo.CartService/AddItem"
                          }[5m]
                        )
                      )
                    )
                instant: true
                interval: ""
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.0001
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: febljk0a32qyoa
          panelId: 17
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 2m
          annotations:
            __dashboardUid__: febljk0a32qyoa
            __panelId__: "17"
            description: |-
                The 95th percentile response time for operation {{ $labels.service_namespace
                    }}/{{ index $labels.service_name }} "{{ $labels.http_request_method }} {{
                    $labels.http_route }}" ({{ $labels.deployment_environment_name }}) has been
                    above 2 seconds for 2 minutes on {{ $labels.service_instance_id}}. Current
                    value: {{ $value }}.
            summary: |-
                High P95 for {{ $labels.service_namespace }}/{{ $labels.service_name }} "{{
                    $labels.http_request_method }} {{ $labels.http_route }}" ({{
                    $labels.deployment_environment_name }})
          labels:
            service_name: cart
            service_namespace: opentelemetry-demo
            severity: warning
            team_name: webstore
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
