# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

global:
  # Align Prometheus scrape interval with the OTel SDKs' export interval for consistency (see OTEL_METRIC_EXPORT_INTERVAL)
  scrape_interval: 60s

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name
    - k8s.cluster.name
    - k8s.container.name
    - k8s.cronjob.name
    - k8s.daemonset.name
    - k8s.deployment.name
    - k8s.job.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.replicaset.name
    - k8s.statefulset.name
    #
    - container.id
    - container.runtime
    - container.hostname
    - container.image.id
    #
    - host.name
    - host.id
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/postgresqlreceiver/metadata.yaml
    - postgresql.database.name
    - postgresql.schema.name
    - postgresql.table.name
    - postgresql.index.name
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/redisreceiver/metadata.yaml
    - redis.version
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/nginxreceiver/metadata.yaml

storage:
  tsdb:
    out_of_order_time_window: 30m
